/**
 * Content pipeline: reads src/content/dialogues/*.md source files,
 * regenerates the dialogues section of i18n/en.js and i18n/fr.js,
 * and updates src/content/manifest.json with per-node hashes.
 *
 * Hash-based: only nodes whose content changed are marked dirty.
 * TTS/translation calls (future) will only run on dirty nodes.
 *
 * Run: npm run generate
 */

import { createHash } from 'crypto';
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CONTENT_DIR = join(ROOT, 'src/content/dialogues');
const MANIFEST_PATH = join(ROOT, 'src/content/manifest.json');
const EN_PATH = join(ROOT, 'src/data/i18n/en.js');
const FR_PATH = join(ROOT, 'src/data/i18n/fr.js');

function nodeHash(node) {
  const text = [
    node.fr,
    node.en,
    ...node.choices.map(c => `${c.fr}|${c.en}`),
  ].join('\n');
  return createHash('sha256').update(text).digest('hex').slice(0, 16);
}

function parseContentFiles() {
  const files = readdirSync(CONTENT_DIR).filter(f => f.endsWith('.md')).sort();
  const result = {};

  for (const file of files) {
    const lines = readFileSync(join(CONTENT_DIR, file), 'utf8').split('\n');
    let dialogue = null;
    let node = null;

    for (const line of lines) {
      const dlgMatch = line.match(/^# dialogue:\s*(.+)/);
      if (dlgMatch) {
        dialogue = dlgMatch[1].trim();
        result[dialogue] = {};
        node = null;
        continue;
      }

      const nodeMatch = line.match(/^## node:\s*(.+)/);
      if (nodeMatch && dialogue) {
        node = nodeMatch[1].trim();
        result[dialogue][node] = { fr: '', en: '', choices: [] };
        continue;
      }

      if (!dialogue || !node) continue;
      const n = result[dialogue][node];

      const frMatch = line.match(/^fr:\s*(.*)/);
      if (frMatch) { n.fr = frMatch[1]; continue; }

      const enMatch = line.match(/^en:\s*(.*)/);
      if (enMatch) { n.en = enMatch[1]; continue; }

      const choiceMatch = line.match(/^choice\[(\d+)\]\.(fr|en):\s*(.*)/);
      if (choiceMatch) {
        const idx = parseInt(choiceMatch[1]);
        const lang = choiceMatch[2];
        if (!n.choices[idx]) n.choices[idx] = { fr: '', en: '' };
        n.choices[idx][lang] = choiceMatch[3];
      }
    }
  }

  return result;
}

function loadManifest() {
  if (existsSync(MANIFEST_PATH)) {
    return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'));
  }
  return { version: 1, nodes: {} };
}

async function loadI18n(filePath) {
  // Use file URL to bypass module cache
  const url = `file://${filePath}?t=${Date.now()}`;
  return (await import(url)).default;
}

function writeI18n(filePath, obj, comment) {
  writeFileSync(filePath, `// ${comment}\nexport default ${JSON.stringify(obj, null, 2)};\n`);
}

async function main() {
  console.log('Reading content files...');
  const parsed = parseContentFiles();
  const dialogueCount = Object.keys(parsed).length;
  const nodeCount = Object.values(parsed).reduce((n, d) => n + Object.keys(d).length, 0);
  console.log(`  ${dialogueCount} dialogues, ${nodeCount} nodes`);

  const manifest = loadManifest();
  const newManifest = { version: 1, nodes: {} };

  const enDialogues = {};
  const frDialogues = {};
  let changed = 0;
  let unchanged = 0;

  for (const [dialogueId, nodes] of Object.entries(parsed)) {
    enDialogues[dialogueId] = {};
    frDialogues[dialogueId] = {};

    for (const [nodeId, node] of Object.entries(nodes)) {
      const key = `${dialogueId}.${nodeId}`;
      const hash = nodeHash(node);
      const prev = manifest.nodes[key];

      if (!prev || prev.hash !== hash) {
        changed++;
        newManifest.nodes[key] = { hash, dirty: true };
      } else {
        unchanged++;
        newManifest.nodes[key] = { hash, dirty: false };
      }

      const enChoices = node.choices.map(c => c.en).filter(Boolean);
      const frChoices = node.choices.map(c => c.fr).filter(Boolean);

      enDialogues[dialogueId][nodeId] = node.en
        ? { text: node.en, ...(enChoices.length ? { choices: enChoices } : {}) }
        : { ...(enChoices.length ? { choices: enChoices } : {}) };

      frDialogues[dialogueId][nodeId] = node.fr
        ? { text: node.fr, ...(frChoices.length ? { choices: frChoices } : {}) }
        : { ...(frChoices.length ? { choices: frChoices } : {}) };
    }
  }

  console.log(`  ${changed} nodes changed, ${unchanged} unchanged`);

  console.log('Updating i18n files...');
  const en = await loadI18n(EN_PATH);
  const fr = await loadI18n(FR_PATH);

  en.dialogues = enDialogues;
  fr.dialogues = frDialogues;

  writeI18n(EN_PATH, en, 'English — generated by scripts/generate.js. Edit src/content/dialogues/*.md instead.');
  writeI18n(FR_PATH, fr, 'Français — generated by scripts/generate.js. Edit src/content/dialogues/*.md instead.');

  mkdirSync(join(ROOT, 'src/content'), { recursive: true });
  writeFileSync(MANIFEST_PATH, JSON.stringify(newManifest, null, 2) + '\n');

  console.log('Done.');
  if (changed > 0) {
    console.log(`\n${changed} node(s) marked dirty in manifest.`);
    console.log('These will need translation/audio regeneration when that pipeline is added.');
  }
}

main().catch(err => { console.error(err); process.exit(1); });
